blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Create by Leo on 05/12/2016

from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<article_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
]

love/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^summer/', include('summer.urls', namespace='summer', app_name='summer')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

summer/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Create by Leo on 04/12/2016


from django.conf.urls import url

from . import views

app_name = 'summer'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

summer/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

import datetime
from django.utils import timezone


# Create your models here.




@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# class Blog(models.Model):
#     name = models.CharField(max_length=50)
#     summary = models.CharField(max_length=200)
#     content = models.TextField()
#     create_at = models.DateField('date published')
#
#
# class Comment(models.Model):
#     blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
#     content = models.TextField()
#     create_at = models.DateField('date published')


# class Blog(models.Model):
#     user_id = models.CharField(max_length=50)
#     user_name = models.CharField(max_length=50)
#     user_image = models.CharField(max_length=500)
#     name = models.CharField(max_length=50)
#     summary = models.CharField(max_length=200)
#     content = models.TextField()
#     create_at = models.DateField('date published')
#
#
# class Comment(models.Model):
#     blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
#     user_id = models.CharField(max_length=50)
#     user_name = models.CharField(max_length=50)
#     user_image = models.CharField(max_length=500)
#     content = models.TextField()
#     create_at = models.DateField('date published')

summer/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponseRedirect, request
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'summer/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'summer/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'summer/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'summer/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('summer:results', args=(question.id,)))

summer/templates/summer/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'summer:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
    {% endfor %}

    <input type="submit" value="Vote">
</form>

summer/templates/summer/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'summer/style.css' %}">

{% if latest_question_list %}
    <ul class="list-unstyled">
        {% for question in latest_question_list %}
            <li><a href="{% url 'summer:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No summer are available.</p>
{% endif %}

summer/templates/summer/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}</li>
    {% endfor %}

</ul>

<a href="{% url 'summer:detail' question.id %}">Vote again?</a>