blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Create by Leo on 05/12/2016

from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<article_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
]

love/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^summer/', include('summer.urls', namespace='summer', app_name='summer')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

from collections import defaultdict


# Create your models here.
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('类名', max_length=20)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name


class ArticleManage(models.Manager):
    """
    继承自默认的 Manager ，为其添加一个自定义的 archive 方法
    """

    def archive(self):
        # 获取到降序排列的精确到月份且已去重的文章发表时间列表
        # 并把列表转为一个字典，字典的键为年份，值为该年份下对应的月份列表
        date_list = Article.objects.datetimes('create_time', 'month', order='DESC')
        date_dict = defaultdict(list)
        for d in date_list:
            # 模板不支持defaultdict，因此我们把它转换成一个二级列表，由于字典转换后无序，因此重新降序排序
            date_dict[d.year].append(d.month)
        return sorted(date_dict.items(), reverse=True)


@python_2_unicode_compatible
class Article(models.Model):
    STATUS_CHOICE = (
        ('d', 'Draft'),
        ('p', 'Published')
    )

    # 仍然使用默认的 objects 作为 manager 的名字
    objects = ArticleManage()

    title = models.CharField('标题', max_length=70)
    content = models.TextField('正文')
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICE)
    abstract = models.CharField('摘要', max_length=60, blank=True, null=True, help_text="可选，如若为空将摘选正文前60个字符")
    views = models.PositiveIntegerField('浏览量', default=0)
    likes = models.PositiveIntegerField('点赞数', default=0)
    topped = models.BooleanField('置顶', default=False)

    category = models.ForeignKey('Category', verbose_name='分类', null=True, on_delete=models.SET_NULL)
    """
    文章model中添加tag关系
    """
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-last_modified_time']

    # 新增 get_absolute_url 方法
    def get_absolute_url(self):
        # 这里 reverse 解析 blog:detail 视图函数对应的 url
        return reverse('blog:detail', kwargs={'article_id': self.pk})


@python_2_unicode_compatible
class Tag(models.Model):
    """
    tag(标签)对应的数据库model
    """
    name = models.CharField('标签名', max_length=20)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class BlogComment(models.Model):
    user_name = models.CharField('评论者名字', max_length=100)
    user_email = models.EmailField('评论者邮箱', max_length=255)
    content = models.TextField('评论内容')
    created_time = models.DateTimeField('评论发表时间', auto_now_add=True)
    article = models.ForeignKey('Article', verbose_name='评论所属文章', on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:20]

blog/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Create by Leo on 06/12/2016

from django import forms
from .models import Article, BlogComment


class BlogCommentForm(forms.ModelForm):
    """指定一些 Meta 选项以改变 form 被渲染后的样式"""

    class Meta:
        # form 关联的 Model
        model = BlogComment

        # fields 表示需要渲染的字段，这里需要渲染user_name、user_email、body
        # 这样渲染后表单会有三个文本输入框，分别是输入user_name、user_email、body的输入框
        fields = ['user_name', 'user_email', 'content']

        # 为各个需要渲染的字段指定渲染成什么html组件，主要是为了添加css样式。
        # 例如 user_name 渲染后的html组件如下：
        # <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">
        widgets = {
            'user_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '请输入昵称',
                'aria-describedby': 'sizing-addon1',
            }),
            'user_email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '请输入邮箱',
                'aria-describedby': 'sizing-addon1',
            }),
            'content': forms.Textarea(attrs={
                'placeholder': '我来点评两句~'
            }),
        }

blog/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import render

from django.views import generic
from django.shortcuts import get_object_or_404, HttpResponseRedirect

from blog.models import Category, Article, Tag

from forms import BlogCommentForm

import markdown2


# Create your views here.
class IndexView(generic.ListView):
    """
    首页视图,继承自ListVIew，用于展示从数据库中获取的文章列表
    """

    # template_name属性用于指定使用哪个模板进行渲染
    template_name = "blog/index.html"

    # context_object_name属性用于给上下文变量取名（在模板中使用该名字）
    context_object_name = "article_list"

    def get_queryset(self):
        """
        过滤数据，获取所有已发布文章，并且将内容转成markdown形式
        """
        article_list = Article.objects.filter(status='p')
        for article in article_list:
            # 将markdown标记的文本转为html文本
            article.content = markdown2.markdown(article.content, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        # 增加额外的数据，这里返回一个文章分类，以字典的形式
        kwargs['category_list'] = Category.objects.all().order_by('name')
        # 调用 archive 方法，把获取的时间列表插入到 context 上下文中以便在模板中渲染
        kwargs['date_archive'] = Article.objects.archive()
        # tag_list 加入 context 里：
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(generic.DetailView):
    # 指定视图获取哪个model
    model = Article
    template_name = "blog/detail.html"
    context_object_name = "article"

    # 这里注意，pk_url_kwarg用于接收一个来自url中的主键，然后会根据这个主键进行查询
    pk_url_kwarg = 'article_id'

    # 指定以上几个属性，已经能够返回一个DetailView视图了，为了让文章以markdown形式展现，我们重写get_object()方法。
    # get_object() 返回该视图要显示的对象。
    # 如果有设置 queryset，该queryset 将用于对象的源；
    # 否则，将使用get_queryset(). get_object()从视图的所有参数中查找 pk_url_kwarg 参数；
    # 如果找到了这个参数，该方法使用这个参数的值执行一个基于主键的查询。
    def get_object(self):
        obj = super(ArticleDetailView, self).get_object()
        obj.content = markdown2.markdown(obj.content, extras=['fenced-code-blocks'], )
        return obj

    # 新增 form 到 context
    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.blogcomment_set.all()
        kwargs['form'] = BlogCommentForm()
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryView(generic.ListView):
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        # 注意在url里我们捕获了分类的id作为关键字参数（cate_id）传递给了CategoryView，传递的参数在kwargs属性中获取。
        article_list = Article.objects.filter(category=self.kwargs['article_id'], status='p')
        for article in article_list:
            article.content = markdown2.markdown(article.content, extras=['fenced-code-blocks'], )
        return article_list

    # 给视图增加额外的数据
    def get_context_data(self, **kwargs):
        # 增加一个category_list,用于在页面显示所有分类，按照名字排序
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(CategoryView, self).get_context_data(**kwargs)


class TagView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        """
        根据指定的标签获取该标签下的全部文章
        """
        article_list = Article.objects.filter(tags=self.kwargs['tag_id'], status='p')
        for article in article_list:
            article.content = markdown2.markdown(article.content, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(TagView, self).get_context_data(**kwargs)


class ArchiveView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        # 接收从url传递的year和month参数，转为int类型
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])
        # 按照year和month过滤文章
        article_list = Article.objects.filter(create_time__year=year, create_time__month=month)
        for article in article_list:
            article.content = markdown2.markdown(article.content, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(ArchiveView, self).get_context_data(**kwargs)


class CommentPostView(generic.FormView):
    # 指定使用的是哪个form
    form_class = BlogCommentForm
    # 指定评论提交成功后跳转渲染的模板文件。
    # 我们的评论表单放在detail.html中，评论成功后返回到原始提交页面。
    template_name = 'blog/detail.html'

    def form_valid(self, form):
        """提交的数据验证合法后的逻辑"""
        # 首先根据 url 传入的参数（在 self.kwargs 中）获取到被评论的文章
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])

        # 调用ModelForm的save方法保存评论，设置commit=False则先不保存到数据库，
        # 而是返回生成的comment实例，直到真正调用save方法时才保存到数据库。
        comment = form.save(commit=False)

        # 把评论和文章关联
        comment.article = target_article
        comment.save()

        # 评论生成成功，重定向到被评论的文章页面，get_absolute_url 请看下面的讲解。
        self.success_url = target_article.get_absolute_url()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form):
        """提交的数据验证不合法后的逻辑"""
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])

        # 不保存评论，回到原来提交评论的文章详情页面
        return render(self.request, 'blog/detail.html', {
            'form': form,
            'article': target_article,
            'comment_list': target_article.blogcomment_set.all(),
        })

blog/templates/blog/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="{% url 'blog:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ 0 }}条评论</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
                {% load static %}
                <img src="{% static 'blog/img/小黄人.jpg' %}" class="user-avatar">
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.created_time }}</time>
                <div class="comment-content">{{ comment.content }}</div>
                <a href="">回复</a>
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="detail-title">
                        <ul id="single-nav">
                            <li><a href="{% url 'blog:index' %}">首页</a></li>
                            <li>></li>
                            <li>
                                <ul class="post-categories">
                                    <li><a href="" title="" rel="category">{{ article.category.name }}</a></li>
                                </ul>
                            </li>
                            <li>></li>
                            <li class="title-active"><a href="{% url 'blog:detail' article.pk %}"
                                                        rel="bookmark">{{ article.title }}</a></li>
                        </ul>
                    </div>
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-media-report">
                        <div class="post-hd">
                            <h1 class="title">{{ article.title }}</h1>
                        </div>
                        <div class="date-read">
                            <i class="icon-date"></i><span
                                class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                        </div>
                        <div class="post-bd">
                            {{ article.content|safe }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog/comment.html' %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
    <div id="banner" class="noselect"></div>

    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div id="category" class="noselect">
                    <div id="category-title">
                        <ul>
                            <li>分类:</li>
                            {% for category in category_list %}
                                <li class="cat-item">
                                    <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        <!-- 首先必须通过load模板标签载入分页标签 -->
                        {% load paginate_tags %}
                        <!-- 把文章列表传给paginate函数，每页分7个，context上下文则自动被传入，无需显示指定 -->
                        {% paginate article_list 7 %}

                        {% for article in article_list %}
                            <div class="post">
                                <div class="post-hd">
                                    <h1 class="title">
                                        <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
                                    </h1>
                                </div>
                                <div class="post-bd">
                                    <p>{{ article.abstract }}</p>
                                    <p><a href="" class="more-link"></a></p>
                                </div>
                                <div class="post-ft">
                                    <a href="{% url 'blog:detail' article.id %}" class="more">阅读全文>></a>
                                    <i class="icon-date"></i>
                                    <span class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                                </div>
                            </div>
                        {% endfor %}

                        <!-- 这里用到一个 include 技巧，把pagination的模板代码写在单独的pagination.html文件中，这样哪里需要用到哪里就 include 进来就行，提高代码的复用性。 -->
                        {% include 'blog/pagination.html' %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <!-- tags -->
                <h3>标签:</h3>
                <div class="list-group">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="list-group-item">
                            <span class="badge"></span>{{ tag.name }}
                        </a>
                    {% endfor %}
                </div>

                <!-- archive -->
                <h3>文章归档:</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for year,months in date_archive %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}" aria-expanded="true"
                                       aria-controls="collapse{{ forloop.counter }}">
                                        {{ year }} 年
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for month in months %}
                                        <a href="{% url 'blog:archive' year month %}"><p>{{ month }} 月</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/pagination.html
<div id="pagenavi" class="noselect">
    <!-- 判断是否还有上一页，有的话要显示一个上一页按钮 -->
    {% if article_list.has_previous %}
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    <!-- 页码号为1永远显示 -->
    <!-- 当前页就是第一页 -->
    {% if first_page == current_page %}
        <span class="first-page current">1</span>
    {% else %}
        <!-- 否则的话，第一页是可以点击的，点击后通过?page=1的形式把页码号传递给视图函数 -->
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    <!-- 2以前的页码号要被显示成省略号了 -->
    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    <!-- 通过for循环把pages中的值显示出来 -->
    {% for page in pages %}
        <!-- 是否当前页，按钮会显示不同的样式 -->
        {% if page == current_page %}
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    <!-- pages最后一个值+1的值小于最大页码号，说明有页码号需要被省略号替换 -->
    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    <!-- 永远显示最后一页的页码号，如果只有一页则前面已经显示了1就不用再显示了 -->
    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    <!-- 还有下一页，则显示一个下一页按钮 -->
    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">下一页<span class="icon-next"></span> </a>
    {% endif %}

</div>